plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ec.ffmpeg'
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // 使用本地 FFmpegKit AAR
    implementation files('libs/ffmpeg-kit-audio-8.1.7-arm64-v8a-x86_64.aar')
}
