plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ec.ffmpeg'
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // FFmpegKit from Maven Central (Java 8 compatible)
    implementation 'com.arthenica:ffmpeg-kit-full:5.1-1'
}
